visual_objects:
  - name: panel_A
    file: A.dae
    tags:
      - id: 11
        position:
          x: 0.042
          y: 0.0
          z: -0.042
        rotation:
          x: -0.70710678118
          y: 0.0
          z: 0.0
          w: -0.70710678118
  - name: panel_B1
    file: B1.dae
    tags:
      - id: 14
        position:
          x: 0.104
          y: 0.0
          z: -0.042
        rotation:
          x: -0.70710678118
          y: 0.0
          z: 0.0
          w: -0.70710678118
      - id: 13
        position:
          x: 0.104
          y: 0.0
          z: -0.113
        rotation:
          x: -0.70710678118
          y: 0.0
          z: 0.0
          w: -0.70710678118
  - name: panel_B2
    file: B2.dae
    tags:
      - id: 15
        position:
          x: 0.042
          y: 0.0
          z: -0.113
        rotation:
          x: -0.70710678118
          y: 0.0
          z: 0.0
          w: -0.70710678118
