jointstate_topic: /manipulator/joint_states
queue_size: 16
extended_range_mode: false
command_topics:
    base_cyl: manipulator/joint1_position_controller/command
    cyl_arm1: manipulator/joint2_position_controller/command
    arm1_arm2: manipulator/joint3_position_controller/command
    arm2_arm3: manipulator/joint4_position_controller/command
    arm3_tool: manipulator/joint5_position_controller/command
control_modes:
  cartesian:
    max_velocity: 0.05
    acceleration: 0.01
    max_error: 0.001
    interpolation_rate: 10.0
    velocity_weighing: [1, 1, 1, 0.01, 0.7]
  jointspace:
    max_velocity: 0.25
    acceleration: 0.03
    max_error: 0.001
    interpolation_rate: 10.0
    velocity_weighing: [1, 1, 1, 1, 0.05]
  cartesianextrange:
    max_velocity: 0.05
    acceleration: 0.01
    max_error: 0.001
    interpolation_rate: 10.0
    velocity_weighing: [1, 1, 1, 0.01, 0.7]
  jointspaceextrange:
    max_velocity: 0.25
    acceleration: 0.03
    max_error: 0.001
    interpolation_rate: 10.0
    velocity_weighing: [1, 1, 1, 1, 0.05]
  incremental:
    send_rate: 20.0

