links:
  names:
    - "base_cyl"
    - "cyl_arm1"
    - "arm1_arm2"
    - "arm2_arm3"
  lengths:
    - 0.0655
    - 0.4350
    - 0.4650
    - 0.129
  limits:
    - [-3.0, 3.0]
    - [-3.0, 3.0]
    - [-3.0, 3.0]
    - [-3.0, 3.0]
