links:
  names:
    - "base_cyl"
    - "cyl_arm1"
    - "arm1_arm2"
    - "arm2_arm3"
    - "arm3_tool"
  lengths:
    - 0.073
    - 0.445
    - 0.473
    - 0.353 # - 0.132

  limits:
    - [-1000.0, 1000.0]
    - [-1.45, 0.79]
    - [0.0, 2.36]
    - [-1.45, 0.79]
    - [-1000.0, 1000.0]
