TrajectoryPlannerROS:
  max_vel_x: 1
  min_vel_x: 0.1
  max_vel_theta: 0.75
  min_in_place_vel_theta: 0.2
  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 0
  sim_time: 3.0
  path_distance_bias: 1.1
  goal_distance_bias: 0.8
  occdist_scale: 0.3
  vx_samples: 30
  vtheta_samples: 30
  dwa: false
  holonomic_robot: false
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.15 
  controller_frequency: 10
  meter_scoring: true