local_planner:
  max_vel_x: 1
  min_vel_x: 0.1
  escape_vel: 0.2
  max_vel_theta: 1
  min_vel_theta: -1
  min_in_place_vel_theta: 0.3
  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 0
  sim_time: 3.0
  path_distance_bias: 1.1
  goal_distance_bias: 0.8
  occdist_scale: 0.3
  vx_samples: 10
  vtheta_samples: 30
  dwa: false
  holonomic_robot: false
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.15 
  latch_xy_goal_tolerance: true
  meter_scoring: true