robot_base_frame: base_link
rolling_window: true
obstacles:
  observation_sources: front_camera back_camera
  track_unknown_space: false
  max_obstacle_height: 1.3
  footprint_clearing_enabled: true
  front_camera: 
    topic: /front_camera/point_cloud/cloud_registered
    data_type: PointCloud2
    clearing: true
    marking: true
    min_obstacle_height: 0.2
  back_camera: 
    topic: /back_camera/point_cloud/cloud_registered
    data_type: PointCloud2
    clearing: true
    marking: true
    min_obstacle_height: 0.2