planners:
  - name: 'global_planner'
    type: 'global_planner/GlobalPlanner'
controllers:
  - name: 'local_planner'
    type: 'base_local_planner/TrajectoryPlannerROS'
recovery_behaviors:
  - name: clear_costmap_recovery
    type: clear_costmap_recovery/ClearCostmapRecovery
  - name: rotate_recovery
    type: rotate_recovery/RotateRecovery
  - name: clear_costmap_recovery2
    type: clear_costmap_recovery/ClearCostmapRecovery

recovery_enabled: true
recovery_patience: 15.0

controller_frequency: 10

planner_patience: 10.0
planner_max_retries: 2

controller_patience: 5.0
controller_max_retries: 2

robot_frame: 'base_link'
dist_tolerance: 0.2
angle_tolerance: 0.8

global_planner:
  lethal_cost: 200
