services:
  # Launch core components of the rover software inside container
  rover-soft:
    image: registry.gitlab.com/ska_robotics/sirius/rover-soft/rover-soft:stable
    command: roslaunch main_controller complete.launch
    restart: unless-stopped
    network_mode: host
    privileged: true # This is intentional
    tty: true
    devices:
      - '/dev:/dev'
