services:
  # Launch core components of the rover software inside container
  rover-soft:
    image: registry.gitlab.com/ska_robotics/sirius/rover-soft/rover-soft:jetson
    # TODO: Run proper .launch file
    command: mon launch sirius_description sirius2.launch web_interface:=False joystick_controller:=False
    restart: unless-stopped
    network_mode: host
    privileged: true # This is intentional
    tty: true
    devices:
      - '/dev:/dev'
