robot_hardware:
  - wheels_left
  - wheels_right
wheels_left:
  type: roboclaw/RoboclawHWInterface
  motor1: left_back_wheel_joint
  motor2: left_front_wheel_joint
wheels_right:
  type: roboclaw/RoboclawHWInterface
  motor1: right_back_wheel_joint
  motor2: right_front_wheel_joint
roboclaw_driver:
  baudrate: 115200
  "128": # left wheels
    communication_timeout: 0.6
    motor1: # front wheel
      command_timeout: 800
      ticks_per_revolution: 172000
      torque_constant: 1.2986
    motor2: # back wheel
      command_timeout: 800
      ticks_per_revolution: 172000
      torque_constant: 1.2986
  "129": # right
    communication_timeout: 0.6
    motor1: # front wheel
      command_timeout: 800
      ticks_per_revolution: 172000
      torque_constant: 1.2986
    motor2: # back wheel
      command_timeout: 800
      ticks_per_revolution: 172000
      torque_constant: 1.2986
  "130":
    communication_timeout: 0.5
    multiunit_mode: false
    relay_mode: false
    swap_buttons: false
    motor2:
      command_timeout: 800
      torque_constant: 1.2986
      reverse_motor: false
      max_current: 25
    motor1:
      command_timeout: 800
      torque_constant: 1.2986
      reverse_motor: true
      max_current: 25
  "131":
    communication_timeout: 0.5
    multiunit_mode: false
    relay_mode: false
    swap_buttons: false
    motor2:
      command_timeout: 800
      torque_constant: 1.2986
      reverse_motor: false
      max_current: 25
    motor1:
      command_timeout: 800
      torque_constant: 1.2986
      reverse_motor: true
      max_current: 25
  "132":
    communication_timeout: 0.5
    multiunit_mode: false
    relay_mode: false
    swap_buttons: false
    motor2:
      command_timeout: 800
      torque_constant: 1.2986
      reverse_motor: false
      max_current: 25
    motor1:
      command_timeout: 800
      torque_constant: 1.2986
      reverse_motor: true
      max_current: 25
