odom0: /odom

# # Each sensor reading updates some or all of the filter's state. These options give you greater control over which
# # values from each measurement are fed to the filter. For example, if you have an odometry message as input, but only
# # want to use its Z position value, then set the entire vector to false, except for the third entry. The order of the
# # values is x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az. Note that not some message types
# # do not provide some of the state variables estimated by the filter. For example, a TwistWithCovarianceStamped message
# # has no pose information, so the first six values would be meaningless in that case. Each vector defaults to all false
# # if unspecified, effectively making this parameter required for each sensor.
odom0_config: [false,  false,  false,
               false, false, false,
               true, true, true,
               false, false, true,
               false, false, false]

# # If you have high-frequency data or are running with a low frequency parameter value, then you may want to increase
# # the size of the subscription queue so that more measurements are fused.
odom0_queue_size: 2
odom0_nodelay: false
odom0_differential: false
odom0_relative: false
odom0_pose_rejection_threshold: 5
odom0_twist_rejection_threshold: 1