%YAML:1.0

imu0:
  T_i_b:
    - [1.0, 0.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0, 0.0]
    - [0.0, 0.0, 1.0, 0.0]
    - [0.0, 0.0, 0.0, 1.0]
  accelerometer_noise_density: 0.01886
  accelerometer_random_walk: 0.01
  gyroscope_noise_density: 0.003074532925199
  gyroscope_random_walk: 2.0e-04
  model: calibrated
  rostopic: /oak_d_w/imu
  time_offset: 0.0
  update_rate: 200.0