%YAML 1.1
---

imu0:
  T_i_b:
    - [1.0, 0.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0, 0.0]
    - [0.0, 0.0, 1.0, 0.0]
    - [0.0, 0.0, 0.0, 1.0]
  accelerometer_noise_density: 0.005886
  accelerometer_random_walk: 0.005
  gyroscope_noise_density: 0.00174532925199
  gyroscope_random_walk: 1.0e-05
  model: calibrated
  rostopic: /oak_d_w/imu
  time_offset: 0.0
  update_rate: 200.0