steering_modes:
  rover:
    normal:
      linear:
        scale_coefficient: 0.08 # max velocity in [m/s] or [rad/s]
        shape_coefficient: 3.0 # 1.0 - linear characteristics, 2.0 - square-antisymmetric, etc.
      angular:
        scale_coefficient: 0.11
        shape_coefficient: 3.0
    tank:
      scale_coefficient: 0.08
      shape_coefficient: 3.0
    gamer:
      linear:
        scale_coefficient: 0.08
        shape_coefficient: 3.0 
      angular:
        scale_coefficient: 0.8 # in rad, used only in 'gamer' mode
        shape_coefficient: 1.0
  manip:
    inverse_kinematics:
      x:
        scale_coefficient: 1.0
        shape_coefficient: 1.0
      y:
        scale_coefficient: 1.0
        shape_coefficient: 1.0
      z:
        scale_coefficient: 1.0
        shape_coefficient: 1.0
      roll:
        scale_coefficient: 1.0
        shape_coefficient: 1.0
      pitch:
        scale_coefficient: 1.0
        shape_coefficient: 1.0
      gripper:
        scale_coefficient: 1.0
        shape_coefficient: 1.0
    # another_mode: