<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="manipulator">
  <xacro:property name="package" value="sirius_description" />
  <xacro:property name="inertial" value="${xacro.load_yaml('manipulator_inertial.yaml')}" />

  <xacro:property name="base_length" value="0.006" />
  <xacro:property name="cyl_length" value="0.0655" />
  <xacro:property name="arm1_length" value="0.43498" />
  <xacro:property name="arm2_length" value="0.5236" />
  <xacro:property name="arm2_lever" value="0.0586" />
  <xacro:property name="arm3_length" value="0.129" />
  <xacro:property name="tool_length" value="0.011" />
  <xacro:property name="base_size_x" value="0.2" />

  <link name="root_link">
  </link>
  <joint name="root_base" type="fixed">
    <parent link="root_link"/>
    <child link="base_link"/>
    <origin xyz="0 0 0"/>
    <axis xyz="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://${package}/meshes/manipulator/base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="yellow">
        <color rgba=".5 .5 0 1" />
      </material>
    </visual>
    <inertial>
      <mass value="${inertial['base_mass']}"/>
        <inertia ixx="${inertial['base_inertia']['ixx']}" ixy="${inertial['base_inertia']['ixy']}" ixz="${inertial['base_inertia']['ixz']}" iyy="${inertial['base_inertia']['iyy']}" iyz="${inertial['base_inertia']['iyz']}" izz="${inertial['base_inertia']['izz']}"/>
    </inertial>
    <collision>
      <origin xyz="0 0 ${base_length / 2}" rpy="0 0 0" />
      <geometry>
        <box size="0.192 0.337 ${base_length}" />
      </geometry>
    </collision>
  </link>

  <link name="cylinder">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://${package}/meshes/manipulator/cyl.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="grey">
        <color rgba=".5 .5 .5 1" />
      </material>
    </visual>
    <inertial>
      <mass value="${inertial['cyl_mass']}"/>
        <inertia ixx="${inertial['cyl_inertia']['ixx']}" ixy="${inertial['cyl_inertia']['ixy']}" ixz="${inertial['cyl_inertia']['ixz']}" iyy="${inertial['cyl_inertia']['iyy']}" iyz="${inertial['cyl_inertia']['iyz']}" izz="${inertial['cyl_inertia']['izz']}"/>
    </inertial>
    <collision>
      <origin xyz="0 0 ${cyl_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder length="${cyl_length}" radius="0.06" />
      </geometry>
    </collision>
  </link>
  <joint name="base_cyl" type="continuous">
    <parent link="base_link"/>
    <child link="cylinder"/>
    <origin xyz="0 0 ${base_length}"/>
    <axis xyz="0 0 1"/>
  </joint>  

  <link name="arm1">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://${package}/meshes/manipulator/arm1.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="green">
        <color rgba="0 1 0 1" />
      </material>
    </visual>
    <inertial>
        <mass value="${inertial['arm1_mass']}"/>
        <inertia ixx="${inertial['arm1_inertia']['ixx']}" ixy="${inertial['arm1_inertia']['ixy']}" ixz="${inertial['arm1_inertia']['ixz']}" iyy="${inertial['arm1_inertia']['iyy']}" iyz="${inertial['arm1_inertia']['iyz']}" izz="${inertial['arm1_inertia']['izz']}"/>
    </inertial>
    <collision>
      <origin xyz="0 0 ${arm1_length/2}" rpy="0 0 0" />
      <geometry>
        <box size="0.07 0.07 ${arm1_length}" />
      </geometry>
    </collision>
  </link>
  <joint name="cyl_arm1" type="revolute">
    <parent link="cylinder"/>
    <child link="arm1"/>
    <origin xyz="0 0 ${cyl_length}"/>
    <axis xyz="0 1 0"/>
    <limit
      lower="-1.45"
      upper="0.79"
      effort="0"
      velocity="0" />
  </joint>

  <link name="arm2">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://${package}/meshes/manipulator/arm2.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 1 1" />
      </material>
    </visual>
    <inertial>
        <mass value="${inertial['arm2_mass']}"/>
        <inertia ixx="${inertial['arm2_inertia']['ixx']}" ixy="${inertial['arm2_inertia']['ixy']}" ixz="${inertial['arm2_inertia']['ixz']}" iyy="${inertial['arm2_inertia']['iyy']}" iyz="${inertial['arm2_inertia']['iyz']}" izz="${inertial['arm2_inertia']['izz']}"/>
    </inertial>
    <collision>
      <origin xyz="0 0 ${arm2_length/2 - arm2_lever}" rpy="0 0 0" />
      <geometry>
        <box size="0.06 0.06 ${arm2_length}" />
      </geometry>
    </collision>
  </link>
  <joint name="arm1_arm2" type="revolute">
    <parent link="arm1"/>
    <child link="arm2"/>
    <origin xyz="0 0 ${arm1_length}"/>
    <axis xyz="0 1 0"/>
    <limit
      lower="0.0"
      upper="2.36"
      effort="0"
      velocity="0" />
  </joint>

  <link name="arm3">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://${package}/meshes/manipulator/arm3.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="red">
        <color rgba="1 0 0 1" />
      </material>
    </visual>
    <inertial>
        <mass value="${inertial['arm3_mass']}"/>
        <inertia ixx="${inertial['arm3_inertia']['ixx']}" ixy="${inertial['arm3_inertia']['ixy']}" ixz="${inertial['arm3_inertia']['ixz']}" iyy="${inertial['arm3_inertia']['iyy']}" iyz="${inertial['arm3_inertia']['iyz']}" izz="${inertial['arm3_inertia']['izz']}"/>
    </inertial>
    <collision>
      <origin xyz="0 0 ${arm3_length/2}" rpy="0 0 0" />
      <geometry>
        <box size="0.06 0.076 ${arm3_length}" />
      </geometry>
    </collision>
  </link>
  <joint name="arm2_arm3" type="revolute">
    <parent link="arm2"/>
    <child link="arm3"/>
    <origin xyz="0 0 ${arm2_length - arm2_lever}"/>
    <axis xyz="0 1 0"/>
    <limit
      lower="-1.45"
      upper="0.79"
      effort="0"
      velocity="0" />
  </joint>

  <link name="tool">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://${package}/meshes/manipulator/tool.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="grey">
      </material>
    </visual>
    <inertial>
        <mass value="${inertial['tool_mass']}"/>
        <inertia ixx="${inertial['tool_inertia']['ixx']}" ixy="${inertial['tool_inertia']['ixy']}" ixz="${inertial['tool_inertia']['ixz']}" iyy="${inertial['tool_inertia']['iyy']}" iyz="${inertial['tool_inertia']['iyz']}" izz="${inertial['tool_inertia']['izz']}"/>
    </inertial>
    <collision>
      <origin xyz="0 0 ${tool_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder length="${tool_length}" radius="0.03" />
      </geometry>
    </collision>
  </link>
  <joint name="arm3_tool" type="continuous">
    <parent link="arm3"/>
    <child link="tool"/>
    <origin xyz="0 0 ${arm3_length}"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="fake">
  </link>
  <joint name="tool_fake" type="continuous">
    <parent link="tool"/>
    <child link="fake"/>
    <origin xyz="0 0 ${tool_length}"/>
    <axis xyz="1 0 0"/>
  </joint>

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/</robotNamespace>
    </plugin>
  </gazebo>
</robot>
