<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="marker">
  <xacro:property name="package" value="marker_description" />
  <xacro:property name="params" value="${xacro.load_yaml('marker.yaml')}" /> 
  <xacro:include filename="macros/marker.urdf.xacro" />
  <xacro:include filename="macros/pole.urdf.xacro" />
  <xacro:marker size='${params["marker_size"]}' margin='${params["margin"]}' name='marker_box'/>
  <xacro:pole height='${params["pole_height"]}' radius='${params["pole_radius"]}' name='marker'/>

  <joint name="marker_pole_joint" type="fixed">
    <parent link="marker"/>
    <child link="marker_box"/>
    <origin xyz="0 0 ${params['pole_height'] + params['marker_size']/2 + params['margin']}" rpy="0 0 0"/>
    <axis xyz="0 0 0"/>
  </joint> 
</robot>
