on: 
  push:
    branches:
      - 'main'
      - 'ci'
jobs:
  # This job creates docker image based on main branch and publishes it to project's container registry.
  # It doesn't use any cache and performs clean build, so it may take longer than other jobs.
  deploy-main-image:
    name: Build and deploy main docker image
    runs-on: ubuntu-latest
    env:
      PLATFORM: linux/amd64,linux/arm64
      MAIN_IMAGE: ghcr.io/${{ github.repository_owner }}/rover-soft:stable

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push image
        uses: docker/build-push-action@v3
        with:
          file: ci/Dockerfile.stable
          push: true
          tags: ${{ $MAIN_IMAGE }}
          platforms: ${{ $PLATFORM }}
          cache-from: ${{ $MAIN_IMAGE }}
          build-args: BUILDKIT_INLINE_CACHE=1